import type { Localized, Route } from './site';
export const pageIntro: Localized<Record<Route, {title:string; description:string}>> = {
  'zh-Hant': {
    about:{title:'關於實驗室',description:'以材料與製程研究連結資源循環、功能設計與工程應用。'}, research:{title:'研究領域',description:'從材料來源、結構與界面，到製程與應用的跨尺度研究。'}, members:{title:'實驗室成員',description:'以正式、可核實的資訊呈現研究團隊。'}, publications:{title:'出版品',description:'以經確認的書目資料建立可追溯的研究成果紀錄。'}, facilities:{title:'實驗設施',description:'依研究流程整理材料、表面、摩擦、感測與模擬的設施類別。'}, news:{title:'最新消息',description:'正式發布實驗室研究、活動與重要訊息。'}, 'join-us':{title:'加入我們',description:'與 AMPL 一起從材料與製程研究回應永續與工程課題。'}, contact:{title:'聯絡資訊',description:'歡迎就研究交流、合作與研究生申請聯繫。'}
  },
  en: {
    about:{title:'About AMPL',description:'Materials and process research connecting circular resources, functional design, and engineering applications.'}, research:{title:'Research',description:'Cross-scale research from material resources and interfaces to processing and applications.'}, members:{title:'Members',description:'The research team is presented through formal, verifiable information.'}, publications:{title:'Publications',description:'Verified bibliographic records create a traceable research publication archive.'}, facilities:{title:'Facilities',description:'Facility categories across materials, surfaces, tribology, sensing, and simulation.'}, news:{title:'News',description:'A formal space for verified laboratory research, activity, and important updates.'}, 'join-us':{title:'Join Us',description:'Explore sustainable and engineering questions through materials and process research with AMPL.'}, contact:{title:'Contact',description:'Please contact AMPL for research exchange, collaboration, or graduate study enquiries.'}
  },
};
export const aboutCopy: Localized<{profile:string; philosophy:string; mission:string}> = {
  'zh-Hant':{profile:'尖端材料及製程實驗室隸屬國立成功大學機械工程學系。研究以綠色合成、資源循環、奈米與生質複合材料、表面工程及模擬輔助設計為核心。',philosophy:'我們相信材料研究應同時理解來源、結構、界面、製程與最終應用。透過實驗與模擬相互驗證，建立可回應環境、生醫、感測與工程需求的材料判斷。',mission:'從農漁業副產物到功能材料，從微觀行為到工程應用，AMPL 致力於建立更具資源意識與設計依據的材料與製程研究。'},
  en:{profile:'The Advanced Material and Processing Lab is part of the Department of Mechanical Engineering at National Cheng Kung University. Its research centres on green synthesis, circular resources, nano and biopolymer composites, surface engineering, and simulation-assisted design.',philosophy:'We believe materials research should connect source, structure, interface, processing, and eventual use. Experiments and simulation are brought together to inform materials for environmental, biomedical, sensing, and engineering contexts.',mission:'From agricultural and fishery by-products to functional materials, and from microscopic behaviour to engineering use, AMPL develops more resource-aware and evidence-based material and process research.'}
};
export const joinCopy: Localized<{lead:string; audiences:string[]; topics:string[]; skills:string[]; contact:string}> = {
  'zh-Hant':{lead:'AMPL 歡迎對材料、製程與永續工程具有好奇心，且願意以嚴謹研究方法探索問題的學生加入。',audiences:['對材料科學、機械工程、化工、環境或相關領域有研究興趣者','希望從實驗、材料表徵與分析建立研究能力者','願意投入跨領域合作與學術溝通者'],topics:['綠色合成與循環經濟','奈米與生物高分子複合材料','表面工程、摩擦學與腐蝕','感測、生醫、環境與模擬最佳化'],skills:['材料與製程設計思考','實驗規劃、表徵與資料判讀','分子、應力與流體模擬的應用視角','研究寫作與學術溝通'],contact:'請以電子郵件聯繫 Prof. Shih-Chen Shi，並簡要說明你的背景與研究興趣。'},
  en:{lead:'AMPL welcomes students curious about materials, processes, and sustainable engineering who want to investigate questions through rigorous research.',audiences:['Students interested in materials science, mechanical engineering, chemical engineering, environmental fields, or related disciplines','Applicants who want to develop experimental, characterization, and analytical research capability','People willing to contribute to interdisciplinary collaboration and scholarly communication'],topics:['Green synthesis and circular economy','Nano and biopolymer composites','Surface engineering, tribology, and corrosion','Sensing, biomedical, environmental, and simulation-assisted optimization'],skills:['Material and process design thinking','Experimental planning, characterization, and data interpretation','Application perspectives for molecular, stress, and fluid analysis','Research writing and scholarly communication'],contact:'Please contact Prof. Shih-Chen Shi by email with a concise introduction to your background and research interests.'}
};
