import type { Localized } from './site';
export type PendingInfo = { eyebrow:Localized; title:Localized; description:Localized; request:Localized };
export const pending: Record<'members'|'alumni'|'publications'|'facility'|'news'|'location'|'logo', PendingInfo> = {
  members:{eyebrow:{'zh-Hant':'成員資料整理中',en:'Member information in preparation'},title:{'zh-Hant':'現任成員資訊將於確認後公告',en:'Current member information will be published after confirmation'},description:{'zh-Hant':'為確保姓名、研究主題與聯絡資訊準確，本站暫不列出未經確認的成員資料。',en:'To ensure accuracy, names, research topics, and contact details are not listed until verified.'},request:{'zh-Hant':'資料將於實驗室確認後更新。',en:'Information will be updated after laboratory confirmation.'}},
  alumni:{eyebrow:{'zh-Hant':'校友資料整理中',en:'Alumni information in preparation'},title:{'zh-Hant':'校友名錄將於確認後更新',en:'Alumni information will be updated after confirmation'},description:{'zh-Hant':'校友資料將依實驗室確認內容正式發布。',en:'Alumni information will be published after laboratory confirmation.'},request:{'zh-Hant':'資料將於實驗室確認後更新。',en:'Information will be updated after laboratory confirmation.'}},
  publications:{eyebrow:{'zh-Hant':'書目資料驗證中',en:'Bibliographic records in verification'},title:{'zh-Hant':'代表論文與完整書目將於確認後更新',en:'Selected publications and full records will be updated after verification'},description:{'zh-Hant':'本站不以樣本或推測資料取代正式出版紀錄。',en:'This site does not substitute sample or inferred data for verified publication records.'},request:{'zh-Hant':'已核實的書目資料將於確認後更新。',en:'Verified bibliographic records will be updated after confirmation.'}},
  facility:{eyebrow:{'zh-Hant':'設備資訊確認中',en:'Information pending verification'},title:{'zh-Hant':'設備細節與照片將於確認後補充',en:'Equipment details and photographs will be added after confirmation'},description:{'zh-Hant':'目前先呈現研究所需的設施類別，不列出未核實的設備名稱。',en:'The current site presents facility categories only and does not list unverified equipment.'},request:{'zh-Hant':'設備資料將於實驗室確認後更新。',en:'Equipment information will be updated after laboratory confirmation.'}},
  news:{eyebrow:{'zh-Hant':'消息發布準備中',en:'News publishing in preparation'},title:{'zh-Hant':'實驗室消息將於確認後發布',en:'Laboratory news will be published after confirmation'},description:{'zh-Hant':'本站保留正式訊息發布空間，避免以虛構日期或活動填補內容。',en:'The site reserves a formal news surface without inventing dates, events, or announcements.'},request:{'zh-Hant':'消息資料將於實驗室確認後更新。',en:'News information will be updated after laboratory confirmation.'}},
  location:{eyebrow:{'zh-Hant':'位置資訊確認中',en:'Location information in preparation'},title:{'zh-Hant':'實驗室位置將於確認後補充',en:'Laboratory location will be added after confirmation'},description:{'zh-Hant':'聯絡頁目前提供系所與教授聯絡方式，實驗室位置資訊待正式確認。',en:'The contact page currently provides department and professor contact information; laboratory location details await confirmation.'},request:{'zh-Hant':'位置資訊將於實驗室確認後更新。',en:'Location information will be updated after laboratory confirmation.'}},
  logo:{eyebrow:{'zh-Hant':'識別素材準備中',en:'Identity assets in preparation'},title:{'zh-Hant':'實驗室 Logo 將於確認後加入',en:'Laboratory logo will be added after confirmation'},description:{'zh-Hant':'現階段以 AMPL 文字識別維持網站一致性。',en:'AMPL typography is used as the consistent identity until an official logo is supplied.'},request:{'zh-Hant':'識別素材將於實驗室確認後更新。',en:'Identity assets will be updated after laboratory confirmation.'}},
};
