import type { Localized } from './site';
export type ResearchArea = { key:string; title:Localized; description:Localized; tags:Localized<string[]>; motif:string };
export const researchAreas: ResearchArea[] = [
  { key:'circular', motif:'fiber', title:{'zh-Hant':'綠色合成與循環經濟',en:'Green Synthesis & Circular Economy'}, description:{'zh-Hant':'以農業與漁業副產物為起點，探索可再利用的材料來源與低負荷製程。研究涵蓋稻稈中纖維素、木質素、矽與微量金屬的資源化，以及漁業廢棄物衍生幾丁聚醣的應用潛力。',en:'AMPL investigates agricultural and fishery by-products as material resources for lower-impact processing. Themes include cellulose, lignin, silicon and trace metals from rice straw, alongside chitosan derived from fishery waste.'}, tags:{'zh-Hant':['農漁業廢棄物','稻稈資源化','幾丁聚醣'],en:['Agricultural & fishery waste','Rice straw reuse','Chitosan'] } },
  { key:'nano', motif:'lattice', title:{'zh-Hant':'奈米材料與生物高分子複合材料',en:'Nanomaterials & Biopolymer Composites'}, description:{'zh-Hant':'以奈米結構與生物高分子為基礎，發展兼具功能性與資源循環思維的複合材料。重點在於材料組成、界面行為與製程條件對最終性能的影響。',en:'The lab develops functional composites through the interaction of nanostructures and biopolymers. Research examines how composition, interfaces, and processing conditions influence material performance.'}, tags:{'zh-Hant':['奈米材料','生物高分子','複合材料'],en:['Nanomaterials','Biopolymers','Composites']} },
  { key:'surface', motif:'layers', title:{'zh-Hant':'摩擦學與表面工程',en:'Tribology & Surface Engineering'}, description:{'zh-Hant':'從摩擦、磨耗與腐蝕行為理解材料表面的工程需求。研究關注塗層、表面改質與耐蝕製程，尋求更可靠的界面與服役表現。',en:'AMPL studies friction, wear, and corrosion as core surface-engineering challenges. Coatings, surface modification, and corrosion-resistant processes are investigated to improve interface reliability and service performance.'}, tags:{'zh-Hant':['摩擦學','塗層','耐蝕製程'],en:['Tribology','Coatings','Corrosion resistance']} },
  { key:'bioenv', motif:'particle', title:{'zh-Hant':'生醫與環境材料',en:'Biomedical & Environmental Materials'}, description:{'zh-Hant':'將材料設計延伸至生醫與環境應用，評估功能、相容性與使用情境。研究方向連結可持續原料、環境處理與生物醫學材料需求。',en:'Material design is connected to biomedical and environmental applications through functional performance and use-context evaluation. The work links sustainable feedstocks with environmental treatment and biomedical material needs.'}, tags:{'zh-Hant':['生醫材料','環境應用','功能材料'],en:['Biomedical materials','Environmental applications','Functional materials']} },
  { key:'sensor', motif:'wave', title:{'zh-Hant':'感測與功能性塗層',en:'Sensors & Functional Coatings'}, description:{'zh-Hant':'探索材料表面、結構與訊號回應之間的關係，發展具功能性的感測與塗層概念。此方向結合材料選擇、介面設計與應用需求。',en:'This area explores how material surfaces and structures can be translated into sensing responses and functional coatings. It connects material selection, interface design, and application requirements.'}, tags:{'zh-Hant':['感測材料','功能性塗層','表面訊號'],en:['Sensing materials','Functional coatings','Surface response']} },
  { key:'simulation', motif:'grid', title:{'zh-Hant':'模擬與製程最佳化',en:'Simulation & Process Optimization'}, description:{'zh-Hant':'以分子動力學、應力分析與流體分析輔助材料與製程的理解。模擬結果用於建立設計判斷，支持材料組成與製程參數的最佳化。',en:'Molecular dynamics, stress analysis, and fluid analysis support the understanding of materials and processes. Simulation guides material and process design decisions toward more informed optimization.'}, tags:{'zh-Hant':['分子動力學','應力分析','流體分析'],en:['Molecular dynamics','Stress analysis','Fluid analysis']} },
];
export const pipeline: Localized<{title:string; description:string}[]> = {
  'zh-Hant': [ {title:'農漁業副產物',description:'稻稈與漁業副產物的資源化觀點'}, {title:'奈米與生質複材',description:'結構、界面與功能的材料設計'}, {title:'表面工程與磨潤',description:'塗層、耐蝕與摩擦行為'}, {title:'表徵與模擬最佳化',description:'實驗觀察結合分子、應力與流體分析'}, {title:'多元應用',description:'生醫、環境、感測與工程應用'} ],
  en: [ {title:'Agricultural & Fishery By-products',description:'Resource-aware starting points for material design'}, {title:'Nano & Biopolymer Composites',description:'Structure, interface, and functional design'}, {title:'Surface Engineering & Tribology',description:'Coatings, corrosion resistance, and friction'}, {title:'Characterization & Simulation',description:'Experiments supported by molecular, stress, and fluid analysis'}, {title:'Applications',description:'Biomedical, environmental, sensing, and engineering contexts'} ],
};
